# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c722c939cb7b231596c77dd1acdc73ef7892d88478400d7be8dc640c75d933b2fc38b8b5cf1dbc8ec24558968bedcf2ad5df8fd1467c7c56b029364506ba7f9

test:
  secret_key_base: 4f2d06c6a891839e0c3f8f2b2cc9effc94fd1763231b34eaee2c7addbeb66382360fae986656a1a386b435c1dc45857438baf7062f79ba6182bec5c0c351d4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
